In [1]:
import csv
import random
import pandas as pd
from datetime import datetime

data = [['User_id',
         'Transaction_id', 
         'Amount', 
         'Recipient', 
         'Sender', 
         'Start_time_year', 
         'Start_time_month', 
         'Start_time_day',
         'Start_time_hour',
         'Start_time_minute',
         'start_time_second',
         'Completion_time_year',
         'Completion_time_month',
         'Completion_time_day',
         'Completion_time_hour',
         'Completion_time_minute',
         'Completion_time_second',
         'label']]
numbers = []
with open('numbers.csv', 'r') as f:
  reader = csv.reader(f)
  for row in reader:
        numbers.append([int(val) for val in row])

In [2]:
numbers

[[240053060],
 [579558102],
 [547272733],
 [243730025],
 [246178685],
 [542059483],
 [247660883],
 [246453271],
 [243820094],
 [547035966],
 [240138307],
 [247765897],
 [247660883],
 [548834670],
 [507172045],
 [244727123],
 [242209978],
 [541933412],
 [542743704],
 [279309704],
 [504416883],
 [246501885],
 [542059483],
 [244544293],
 [504416883],
 [548417168],
 [245992074],
 [235200337],
 [248999880],
 [244763687],
 [541111745],
 [556159735],
 [550447200],
 [245399448],
 [246301618],
 [550054063],
 [550622533],
 [545425491],
 [200660372],
 [247657942],
 [247673225],
 [542739554],
 [246501885],
 [247100178],
 [540641485],
 [504563382],
 [501364373],
 [246047626],
 [541955873],
 [544151900],
 [553336090],
 [544920600],
 [502592086],
 [502322112],
 [542482334],
 [248896521],
 [541823844],
 [542085610],
 [244365190],
 [546540224],
 [248733822],
 [244522539],
 [554305004],
 [548777401],
 [243964203],
 [551715333],
 [541081085],
 [269797689],
 [241611199],
 [551507391],
 [246012233],
 [245605358],
 [549030548],
 [546165210],
 [557030186],
 [553094183],
 [549445694],
 [241425130],
 [246539637],
 [249943746],
 [240796433],
 [542239837],
 [595389201],
 [240894565],
 [552628070],
 [554700677],
 [554745060],
 [243173610],
 [240475717],
 [248824282],
 [240178044],
 [501428240],
 [247533419],
 [248556446],
 [244494948],
 [247098550],
 [244642648],
 [247017416],
 [504028613],
 [246763889],
 [248603686],
 [557171635],
 [548236596],
 [244099049],
 [244099049],
 [243433199],
 [244821591],
 [548663395],
 [240626159],
 [558124848],
 [556262528],
 [242240408],
 [549030720],
 [546318326],
 [548800849],
 [203576600],
 [545350040],
 [249476011]]

In [3]:
def randTime():
    ranH = random.randint(0,10)
    ranM = random.randint(10,59)
    ranS = random.randint(10,59)
    ranM = random.randint(1, 12)
    ranD = random.randint(1, 30)
    
    if(ranM <= 2):
        SranM = ranM +50
    else:
        SranM = ranM - 2 
        
        
    timeS = datetime(2019, ranM, ranD, ranH, SranM, ranS, 0)
    timeS_year = timeS.year
    timeS_month = timeS.month
    timeS_day = timeS.day
    timeS_hour = timeS.hour
    timeS_minute =timeS.minute
    timeS_second = timeS.second
    
    timeE = datetime(2019, ranM, ranD, ranH, ranM, ranS, 0)
    timeE_year = timeE.year
    timeE_month = timeE.month
    timeE_day = timeE.day
    time_hour = timeE.hour
    timeE_minute = timeE.minute
    timeE_second = timeE.second
    
    
    return ( timeS_year,
             timeS_month,
             timeS_day,
             timeS_hour,
             timeS_minute,
             timeS_second,
             timeE_year,
             timeE_month,
             timeE_day,
             time_hour,
             timeE_minute,
             timeE_second)

In [4]:
number = numbers[random.randrange(len(numbers))]
print(str(number).strip('[]'))

248824282

In [5]:
def get_numbers():
    number = str(numbers[random.randrange(len(numbers))]).strip('[]')
    recipient_list = [(str(numbers[random.randrange(len(numbers))]).strip('[]')),
                      (str(numbers[random.randrange(len(numbers))]).strip('[]')), 
                      (str(numbers[random.randrange(len(numbers))]).strip('[]')),
                      (str(numbers[random.randrange(len(numbers))]).strip('[]')),
                      (str(numbers[random.randrange(len(numbers))]).strip('[]'))]
    fraud_list = [(str(numbers[random.randrange(len(numbers))]).strip('[]')),
                      (str(numbers[random.randrange(len(numbers))]).strip('[]')), 
                      (str(numbers[random.randrange(len(numbers))]).strip('[]'))]
    sender = (str(numbers[random.randrange(len(numbers))]).strip('[]'))

    return recipient_list, fraud_list, sender

In [6]:
def generate_list(amt1, amt2, amt3, amt4, userID):
    recipient_list, fraud_list, sender = get_numbers()
    recipient = recipient_list[random.randrange(len(recipient_list))]
    for x in range(11):
        ran1 = random.randint(22,550)
        amount = round(random.uniform(amt1,amt2), 2)
        fraud = 'NOT_FRAUD'
        if(x == 4):
            amount = round(random.uniform(amt3,amt4), 2)
            recipient = fraud_list[random.randrange(len(fraud_list))]  
            fraud = 'FRAUD'
            
        if(x == random.randint(0,10)):
            amount = round(random.uniform(amt3,amt4), 2)
            recipient = fraud_list[random.randrange(len(fraud_list))]
            fraud = 'FRAUD'
         
        if(x == random.randint(0,10)):
            amount = round(random.uniform(amt3,amt4), 2)
            recipient = fraud_list[random.randrange(len(fraud_list))]
            fraud = 'FRAUD'
        
        timeS_year, timeS_month, timeS_day, timeS_hour, timeS_minute, timeS_second, timeE_year, timeE_month, timeE_day, time_hour, timeE_minute, timeE_second, = randTime()
        data.append([userID, 
                     ran1, 
                     amount, 
                     recipient, 
                     sender, 
                     timeS_year,
                     timeS_month,
                     timeS_day,
                     timeS_hour,
                     timeS_minute,
                     timeS_second,
                     timeE_year,
                     timeE_month,
                     timeE_day,
                     time_hour,
                     timeE_minute,
                     timeE_second,
                     fraud])

In [7]:
#recipient_list = ['0242407403', '0204478561', '0237541255', '0244715996']
#fraud_list = ['0245667785', '0245564785', '0245194785']
#sender ='0243201392'

generate_list(5.2, 905.0, 20002.20, 50000.00, '15')
generate_list(50.2, 505.0, 2002.20, 5000.00, '16')
generate_list(5.2, 300.0, 1002.20, 5000.00, '17')
generate_list(5.2, 3005.0, 20002.20, 90050.00, '18')
generate_list(5.2, 1005.0, 7002.20, 10000.00, '19')

generate_list(100.2, 905.0, 70002.20, +0000.00, '20')
generate_list(50.2, 505.0, 3002.20, 7000.00, '21')
generate_list(5.2, 200.0, 2002.20, 5000.00, '22')
generate_list(500.2, 3005.0, 70002.20, 90050.00, '23')
generate_list(80.2, 1005.0, 7002.20, 10000.00, '24')

generate_list(0.2, 905.0, 20002.20, 50000.00, '25')
generate_list(50.2, 505.0, 2002.20, 5000.00, '26')
generate_list(60.2, 300.0, 1002.20, 5000.00, '27')
generate_list(70.2, 3005.0, 20002.20, 90050.00, '28')
generate_list(50.2, 1005.0, 7002.20, 10000.00, '29')

generate_list(500.2, 9005.0, 200002.20, 500000.00, '30')
generate_list(100.2, 10005.0, 20002.20, 5000.00, '31')
generate_list(20.2, 300.0, 1002.20, 5000.00, '32')
generate_list(10.2, 4005.0, 20002.20, 90050.00, '33')
generate_list(1.2, 805.0, 7002.20, 10000.00, '34')

In [8]:
with open('generated_data.csv', 'w') as csvFile:
    writer = csv.writer(csvFile)
    writer.writerows(data)
    
csvFile.close()

In [9]:
data = pd.read_csv('generated_data.csv', header=0)

In [10]:
data.head()

,User_id,Transaction_id,Amount,Recipient,Sender,Start_time_year,Start_time_month,Start_time_day,Start_time_hour,Start_time_minute,start_time_second,Completion_time_year,Completion_time_month,Completion_time_day,Completion_time_hour,Completion_time_minute,Completion_time_second,label
0,15,306,47285.63,246453271,550622533,2019,3,17,4,1,30,2019,3,17,4,3,30,FRAUD
1,15,223,49829.87,246453271,550622533,2019,6,14,2,4,47,2019,6,14,2,6,47,FRAUD
2,15,364,814.20,246453271,550622533,2019,6,29,6,4,38,2019,6,29,6,6,38,NOT_FRAUD
3,15,170,234.96,246453271,550622533,2019,10,15,3,8,25,2019,10,15,3,10,25,NOT_FRAUD
4,15,134,31706.65,246453271,550622533,2019,1,16,9,51,13,2019,1,16,9,1,13,FRAUD