In [1]:
data = [[
    'type',
    'category',
    'business_id',
    'sender',
    'recipient',
    'expired',
    'status',
    'amount',
    'time_difference',
    'label'
]]

In [2]:
import random
import string

def randomStringDigits(stringLength=6):
    lettersAndDigits = string.ascii_letters + string.digits
    return ''.join(random.choice(lettersAndDigits) for i in range(stringLength))

In [3]:
type_list = [0, 1, 2, 3,]
category_list = [0, 1, 2, 3,]

expired_list = [0,1]
status_list = [0,1,2]

In [4]:
import random 
from datetime import datetime

def randTime():
    ranH = random.randint(0,10)
    ranM = random.randint(10,59)
    ranS = random.randint(10,59)
    ranM = random.randint(1, 12)
    ranD = random.randint(1, 30)
    
    if(ranM <= 2):
        SranM = ranM +50
    else:
        SranM = ranM - 2 
        
        
    timeS = datetime(2019, ranM, ranD, ranH, SranM, ranS, 0)
    timeS_year = timeS.year
    timeS_month = timeS.month
    timeS_day = timeS.day
    timeS_hour = timeS.hour
    timeS_minute =timeS.minute
    timeS_second = timeS.second
    
    timeE = datetime(2019, ranM, ranD, ranH, ranM, ranS, 0)
    timeE_year = timeE.year
    timeE_month = timeE.month
    timeE_day = timeE.day
    time_hour = timeE.hour
    timeE_minute = timeE.minute
    timeE_second = timeE.second
    
    
    return ( timeS_year,
             timeS_month,
             timeS_day,
             timeS_hour,
             timeS_minute,
             timeS_second,
             timeE_year,
             timeE_month,
             timeE_day,
             time_hour,
             timeE_minute,
             timeE_second)

In [5]:
def generate():
    for x in range(500):
        time_difference = random.randint(0, 180)
        type = type_list[random.randrange(len(type_list))]
        category = category_list[random.randrange(len(category_list))]
    
        status = status_list[random.randrange(len(status_list))]
        expired = expired_list[random.randrange(len(expired_list))]
        amount = round(random.uniform(50.0,5000.5), 2)
        
        business_id = random.randint(200, 400)
        sender = randomStringDigits()
        recipient = randomStringDigits()
        label = 'NOT_FRAUD'
        
        for i in range(20):
            one = random.randint(0,500)
            if(one == x):
                type = random.randint(4,10000)
                label = 'FRAUD'
            two = random.randint(0,500)
            if(two == x):
                category = random.randint(4,10000)
                label = 'FRAUD'
            three = random.randint(0,500)
            if(three == x):
                expired = random.randint(2,10000)
                label = 'FRAUD'
            four = random.randint(0,500)
            if(four == x):
                status = random.randint(3,10000)
                label = 'FRAUD'
            five = random.randint(0,500)
            if(five == x):
                time_difference = random.randint(180,100000)
                label = 'FRAUD'
        
        
        data.append([type, category, business_id, sender, recipient, expired, status, amount, time_difference, label])

In [6]:
generate()

In [7]:
import csv
with open('data.csv', 'w') as csvFile:
    writer = csv.writer(csvFile)
    writer.writerows(data)
    
csvFile.close()

In [8]:
import pandas as pd
data = pd.read_csv('data.csv', header=0)

In [9]:
data.head()

,type,category,business_id,sender,recipient,expired,status,amount,time_difference,label
0,2,0,339,9qzD1m,aXDKxn,0,6677,2230.09,38547,FRAUD
1,2,0,200,y8uADo,Hent2P,1,1,591.94,119,NOT_FRAUD
2,2,3,299,WHfnpK,cohPnu,9387,0,4125.98,36,FRAUD
3,0,3,218,IRl8kH,cgNvNe,1,2,83.89,166,NOT_FRAUD
4,3,1,365,EeIsvi,EEjHsz,0,1,4178.31,147,NOT_FRAUD