In [1]:
import pandas as pd
import re

In [2]:
data = pd.read_csv('Untitled.csv', header=0)
data.head()

,type,category,service_id,business_id,sender,recipient,created,completed,expired,status,amount
0,1,2,0,63,stark,mrgenfi,2019-01-15 16:00:25,2019-01-15 16:00:25,0,1,1.0
1,1,2,0,63,stark,mrgenfi,2019-01-15 16:11:15,2019-01-15 16:11:15,0,1,1.0
2,1,2,0,63,stark,mrgenfi,2019-01-15 16:11:41,2019-01-15 16:11:41,0,1,1.0
3,1,2,0,63,stark,mrgenfi,2019-01-17 17:00:48,2019-01-17 17:00:48,0,1,1.0
4,1,2,0,63,stark,mrgenfi,2019-01-29 14:42:21,2019-01-29 14:42:21,0,1,12.0

In [17]:
dates = data['created']

for date in dates:
    rgx = re.compile(r"((?:(?<!'|\w)(?:\w-?'?)+(?<!-))|(?:(?<='|\w)(?:\w-?'?)+(?=')))")
    x =rgx.findall(date)
    print(x)

['2019-01-15', '16:00:25']
['2019-01-15', '16:11:15']
['2019-01-15', '16:11:41']
['2019-01-17', '17:00:48']
['2019-01-29', '14:42:21']
['2019-02-12', '14:58:54']
['2019-02-12', '15:04:13']
['2019-02-12', '15:04:35']
['2019-02-13', '13:55:18']
['2019-02-22', '13:07:19']
['2019-03-13', '13:42:25']
['2019-03-14', '13:49:57']
['2019-03-14', '13:52:27']
['2019-03-14', '13:55:22']
['2019-03-14', '13:56:06']
['2019-03-15', '15:39:49']
['2019-04-04', '13:13:18']
['2019-04-04', '13:27:12']
['2019-04-04', '13:30:01']
['2019-04-04', '13:33:22']
['2019-04-04', '13:51:45']
['2019-04-09', '15:57:51']
['2019-04-18', '12:05:00']
['2019-04-18', '12:22:23']
['2019-04-18', '12:28:12']
['2019-04-18', '12:38:20']
['2019-04-18', '12:52:01']
['2019-04-18', '12:54:30']
['2019-04-18', '15:14:51']
['2019-04-23', '12:56:50']
['2019-04-23', '16:37:49']
['2019-04-23', '17:08:59']
['2019-04-23', '20:34:31']
['2019-04-23', '20:38:01']
['2019-04-29', '16:51:37']
['2019-05-02', '15:51:48']
['2019-05-02', '15:52:17']
['2019-05-02', '15:57:50']
['2019-05-02', '16:05:40']
['2019-05-02', '16:18:40']
['2019-05-02', '16:24:32']
['2019-05-02', '16:30:32']
['2019-05-07', '10:55:46']
['2019-05-07', '10:57:19']
['2019-05-08', '17:27:37']
['2019-05-14', '16:57:11']
['2019-05-14', '16:57:23']
['2019-05-29', '13:48:16']
['2019-05-29', '13:48:33']
['2019-05-29', '13:50:17']
['2019-05-29', '13:51:07']
['2019-05-29', '13:52:37']
['2019-05-29', '13:56:05']
['2019-05-29', '13:57:12']
['2019-05-29', '14:09:09']
['2019-05-29', '14:21:26']
['2019-05-29', '14:22:23']
['2019-05-29', '14:25:08']
['2019-05-30', '11:17:22']
['2019-05-30', '12:13:31']
['2019-05-30', '14:45:11']
['2019-05-30', '17:20:30']
['2019-05-31', '13:21:16']
['2019-06-03', '17:44:25']
['2019-06-04', '14:00:05']
['2019-06-07', '15:23:33']
['2019-06-11', '14:06:10']
['2019-06-11', '16:06:51']
['2019-06-20', '17:16:03']
['2019-06-20', '17:17:52']
['2019-06-20', '17:48:05']
['2019-06-20', '17:48:10']
['2019-06-20', '18:19:24']
['2019-06-20', '18:22:41']
['2019-06-20', '18:23:24']
['2019-06-21', '15:39:31']
['2019-06-21', '15:40:45']
['2019-06-27', '14:19:18']
['2019-06-27', '14:35:40']
['2019-06-28', '13:26:06']
['2019-06-28', '15:33:23']
['2019-06-28', '15:34:21']
['2019-06-28', '16:16:40']
['2019-07-02', '12:41:33']
['2019-07-08', '12:22:01']
['2019-07-08', '12:23:43']
['2019-07-08', '17:19:54']
['2019-07-09', '13:20:05']
['2019-07-09', '13:20:32']
['2019-07-09', '13:24:03']
['2019-07-09', '13:25:31']
['2019-07-09', '13:25:36']
['2019-07-09', '13:26:01']
['2019-07-09', '15:52:02']
['2019-07-09', '15:56:34']
['2019-07-09', '15:58:48']
['2019-07-09', '15:59:23']
['2019-07-09', '16:02:00']
['2019-07-11', '15:20:06']
['2019-07-11', '15:21:33']
['2019-07-12', '13:37:56']
['2019-07-12', '14:43:39']
['2019-07-15', '03:38:57']
['2019-07-17', '07:58:43']
['2019-07-22', '12:21:16']
['2019-07-22', '12:24:08']
['2019-07-22', '12:27:15']
['2019-07-22', '12:31:28']
['2019-07-22', '12:33:07']
['2019-07-22', '12:35:26']
['2019-07-22', '12:36:20']
['2019-07-22', '12:41:16']
['2019-07-22', '12:43:38']
['2019-07-22', '12:44:32']
['2019-07-22', '12:45:09']
['2019-07-22', '17:17:13']
['2019-07-22', '17:17:59']
['2019-07-22', '17:22:21']
['2019-07-22', '17:25:46']
['2019-07-22', '17:26:34']
['2019-07-22', '17:30:02']
['2019-07-22', '17:44:12']
['2019-07-22', '17:49:25']
['2019-07-22', '18:36:24']
['2019-07-24', '17:45:15']
['2019-07-24', '17:45:55']
['2019-07-28', '19:56:39']
['2019-07-29', '16:51:01']
['2019-07-30', '16:31:21']
['2019-08-06', '17:57:19']
['2019-08-19', '17:38:21']
['2019-09-10', '17:17:16']
['2019-09-10', '17:17:51']
['2019-09-10', '17:21:37']
['2019-09-10', '17:22:04']
['2019-09-12', '17:56:33']
['2019-09-12', '17:57:12']
['2019-09-12', '17:59:01']
['2019-09-12', '17:59:34']
['2019-09-12', '18:00:51']
['2019-09-12', '18:01:25']
['2019-09-12', '18:04:14']
['2019-09-12', '18:06:23']
['2019-09-12', '18:06:46']
['2019-09-12', '18:07:27']
['2019-09-12', '18:08:21']
['2019-09-12', '18:09:01']
['2019-09-12', '18:12:56']
['2019-09-12', '18:13:09']
['2019-09-12', '18:13:45']
['2019-09-12', '18:13:58']
['2019-09-12', '18:15:33']
['2019-09-12', '18:15:52']
['2019-09-12', '18:16:14']
['2019-09-12', '18:16:28']
['2019-09-12', '18:17:05']
['2019-09-12', '18:17:24']
['2019-09-17', '15:12:52']

In [4]:
print re.findall(r"[\w']+", date)

SyntaxError: invalid syntax (<ipython-input-4-7dc8264aadfc>, line 1)